version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./database:/app/database
    env_file:
      - ./backend/.env
  chromadb:
      image: chromadb/chroma
      ports:
        - "8000:8000"
      volumes:
        - ./database/chroma-data:/chroma/chroma